In [1]:
!pip install numpy

In [2]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
%time [i**2 for i in lst]

CPU times: user 10 μs, sys: 0 ns, total: 10 μs
Wall time: 17.2 μs


[1, 4, 9, 16, 25]

In [5]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [6]:
%timeit arr**2

1.82 μs ± 228 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [8]:
arr + 1

array([2, 3, 4, 5, 6])

In [9]:
np.ndim(lst)

1

In [10]:
np.shape(lst)

(5,)

In [13]:
arr = np.arange(3,20,2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
lst_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(lst_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_2d.ndim

2

In [16]:
arr_2d.shape

(3, 3)

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [23]:
arr = np.random.randint(0,20,(5,4))
arr

array([[15, 10, 10, 10],
       [12,  7,  7, 12],
       [11, 14,  7,  9],
       [13, 12, 17,  7],
       [17, 10,  9,  4]])

In [24]:
arr[0]

array([15, 10, 10, 10])

In [25]:
arr[-1]

array([17, 10,  9,  4])

In [27]:
print(arr[0,0])

15


In [28]:
print(arr[2,1])

14


In [29]:
arr

array([[15, 10, 10, 10],
       [12,  7,  7, 12],
       [11, 14,  7,  9],
       [13, 12, 17,  7],
       [17, 10,  9,  4]])

In [30]:
arr[2:,1:3]

array([[14,  7],
       [12, 17],
       [10,  9]])

In [31]:
arr[3:,2:] = 0
arr

array([[15, 10, 10, 10],
       [12,  7,  7, 12],
       [11, 14,  7,  9],
       [13, 12,  0,  0],
       [17, 10,  0,  0]])

In [32]:
mask = arr > 10
mask

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [40]:
bool_arr = np.array(mask)
bool_arr

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [41]:
print(np.sum(mask))

8


In [42]:
arr[mask]

array([15, 12, 12, 11, 14, 13, 12, 17])

In [46]:
A = np.array([10,20,30,40,50])
B = np.arange(1,10,2)

In [47]:
A

array([10, 20, 30, 40, 50])

In [48]:
B

array([1, 3, 5, 7, 9])

In [49]:
A + B

array([11, 23, 35, 47, 59])

In [50]:
A - B

array([ 9, 17, 25, 33, 41])

In [51]:
A / B

array([10.        ,  6.66666667,  6.        ,  5.71428571,  5.55555556])

In [ ]:
A * B # this is not the matrix multiplication

array([ 10,  60, 150, 280, 450])

In [53]:
np.log(B)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458])

In [54]:
np.sin(A)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [5]:
a = np.random.randint(0,20,(4,5))
a

array([[ 8, 17,  7,  2, 13],
       [18,  3, 15,  2, 12],
       [17, 12, 10,  7,  5],
       [11, 12,  9, 12,  5]])

In [6]:
b = np.random.randint(0,10,(5,3))
b

array([[6, 9, 1],
       [1, 2, 9],
       [8, 8, 9],
       [0, 2, 9],
       [8, 8, 2]])

In [7]:
np.dot(a,b)

array([[225, 270, 268],
       [327, 388, 222],
       [234, 311, 288],
       [190, 259, 318]])

In [9]:
A = np.arange(0,20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
A.shape

(20,)

In [23]:
A = A.reshape(5,4)
A.shape

(5, 4)

In [13]:
print(np.max(A))

19


In [15]:
print(np.mean(A))

9.5


In [16]:
print(np.std(A))

5.766281297335398


In [24]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
(np.sum(A,axis=0))

array([40, 45, 50, 55])

In [26]:
np.sum(A,axis=1)

array([ 6, 22, 38, 54, 70])

In [27]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [38]:
a = np.random.randint(0,20,(4,3))
b = np.random.randint(0,20,(4,3))

In [39]:
a

array([[ 8,  3,  5],
       [ 5,  5, 19],
       [16,  6, 13],
       [ 1,  8, 19]])

In [40]:
b

array([[17,  3,  5],
       [17, 16,  3],
       [ 5,  4,  1],
       [ 3, 17,  8]])

In [42]:
np.hstack((a,b))

array([[ 8,  3,  5, 17,  3,  5],
       [ 5,  5, 19, 17, 16,  3],
       [16,  6, 13,  5,  4,  1],
       [ 1,  8, 19,  3, 17,  8]])

In [43]:
np.vstack((a,b))

array([[ 8,  3,  5],
       [ 5,  5, 19],
       [16,  6, 13],
       [ 1,  8, 19],
       [17,  3,  5],
       [17, 16,  3],
       [ 5,  4,  1],
       [ 3, 17,  8]])

In [44]:
A = np.random.randint(0,10,(3,4))
a = np.array(([[1,2,3,4]]))

In [45]:
A

array([[4, 5, 2, 6],
       [8, 7, 1, 0],
       [1, 7, 9, 6]])

In [46]:
a

array([[1, 2, 3, 4]])

In [47]:
A + a

array([[ 5,  7,  5, 10],
       [ 9,  9,  4,  4],
       [ 2,  9, 12, 10]])

In [49]:
A + (a.T)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [50]:
A + 4

array([[ 8,  9,  6, 10],
       [12, 11,  5,  4],
       [ 5, 11, 13, 10]])

In [ ]:
p1 = np.array([1,2,3,4,5,6])
p2 = np.array([7,8,9,10,11,12])
s = 0
for i in range(6):
    s += (p1[i] - p2[i])**2
print(s**0.5)

14.696938456699069


In [62]:
np.sqrt(np.sum((p1-p2)**2))

np.float64(14.696938456699069)