##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

Current Numpy version : 1.19.2


In [7]:
## write code here
import numpy as np
np.__version__

'2.3.1'

#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [18]:
## write code here
arr = np.arange(1,17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

[ 1  3  5  7  9 11 13 15]


In [19]:
## write code here
mask = (arr%2 != 0)
arr_filter = arr[mask]
print(arr_filter)

[ 1  3  5  7  9 11 13 15]


#### Q-4  Replace values that give remainder as 0 when divided by 2 from the above resulted array with 0
Your output should look like this.

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


In [20]:
## write code here
mask = ((arr%2) == 0)
arr[mask] = 0
print(arr)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [21]:
## write code here
arr = arr.reshape(4,4)
arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [22]:
## write code here
np.vstack((arr,arr))

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]
 [ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


In [27]:
arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [29]:
## write code here
arr2 = np.vstack((arr,arr))
new_arr = arr2[:,[1,0,3,2]]
new_arr

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

Mean : 4.0
Median : 0.5
Mode : 0


In [32]:
!pip install scipy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 4.7 MB/s eta 0:00:0000:0100:01


In [35]:
arr2

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [40]:
## write code here
from scipy import stats
print(np.mean(arr2))
print(np.median(arr2))
# print(np.mode(arr2))
# arr3 = arr2.flatten()
# mode = stats.mode(arr3)
mode_result = stats.mode(arr2,axis=None,keepdims=False)
print(mode_result.mode)
print(mode_result.count)

4.0
0.5
0
16


#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

Random Element Array : [15  0  5  3  0]


In [48]:
## write code here
arr4 = arr2.flatten()
random_array = np.random.choice(arr4,size=5,replace=True)
random_array

array([ 7,  0,  5,  5, 15])

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [49]:
sample_array = np.array([1,2,3,4,5])
np.size(sample_array)

5

In [ ]:
def BCE(y, y_hat):
    ## write code here
    n = np.size(y)
    return -((np.sum((y * np.log(y)) + ((1-y) * (np.log(y_hat)))))/n)

In [55]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.9243194196847261
