In [2]:
import numpy as np

arr1 = np.array([2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[2 3 4 5 6]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(5,1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [14]:
arr2.reshape(1,4)
#It cant be done with 5 elements.

ValueError: cannot reshape array of size 5 into shape (1,4)

In [19]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr3.shape)
arr3

(2, 5)


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [21]:
np.arange(10,20,2).reshape(5,1)


array([[10],
       [12],
       [14],
       [16],
       [18]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [29]:
arr = np.array([4,5,6,7,8])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[2.         2.23606798 2.44948974 2.64575131 2.82842712]
[  54.59815003  148.4131591   403.42879349 1096.63315843 2980.95798704]
[-0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825]
[1.38629436 1.60943791 1.79175947 1.94591015 2.07944154]


In [36]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
print(arr[1:,3:])

[[ 9 10]
 [14 15]]


In [38]:
print(arr[0:2,2:4])

[[3 4]
 [8 9]]


In [40]:
arr[0,0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [41]:
arr[2:] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 100, 100, 100, 100]])

In [42]:
data = np.array([1,2,4,5,6])
print(np.mean(data))
print(np.median(data))
print(np.std(data))

normalized_data = (data - np.mean(data))/(np.std(data))
print(normalized_data)

3.6
4.0
1.8547236990991407
[-1.40182605 -0.86266219  0.21566555  0.75482941  1.29399328]


In [ ]:
data = np.array([1,2,3,4,5,6,7,8])
data[(data > 5) & (data <=8)]
# data[(data > 5) and (data <=8)] ## will produce error

array([6, 7, 8])